### ISSUE TITLE
Error while handling 'Mapping incoming JSON from ARI

### ISSUE THREAD

**Issue by Olegars** [opiy-org/asterisk-ari-php#7]
Hi, this is the error that pops up 
`OpiyOrg\AriClient\Client\WebSocket\Ratchet\WebSocketClient.ERROR: Error while handling 'Mapping incoming JSON from ARI web socket server onto object 'OpiyOrg\AriClient\Model\Message\Event\ChannelDialplan' failed | Error message: 'Undefined property: OpiyOrg\AriClient\Client\WebSocket\Ratchet\WebSocketClient::$dataMappingService'' -------> 'Undefined property: OpiyOrg\AriClient\Client\WebSocket\Ratchet\WebSocketClient::$dataMappingService'`

**Comment by opiy-org** [comment]
Could you provide full error trace?

**Comment by Olegars** [comment]
sorry, didn't have time to study, had to use pawl without OpiyOrg
